export const MALAWI_DISTRICTS = [
  'Balaka', 'Blantyre', 'Chikwawa', 'Chiradzulu', 'Chitipa', 'Dedza', 'Dowa',
  'Karonga', 'Kasungu', 'Likoma', 'Lilongwe', 'Machinga', 'Mangochi', 'Mchinji',
  'Mulanje', 'Mwanza', 'Mzimba', 'Neno', 'Nkhata Bay', 'Nkhotakota', 'Nsanje',
  'Ntcheu', 'Ntchisi', 'Phalombe', 'Rumphi', 'Salima', 'Thyolo', 'Zomba'
];

// Unified job types used by both employer posting and seeker filters
export const JOB_TYPES = [
  'Full-time',
  'Part-time',
  'Contract',
  'Internship',
  'Consultant',
  'Remote',
  'Other'
];

// Duration options shown only when job type is NOT Full-time
export const JOB_DURATIONS = [
  '1 Week',
  '2 Weeks',
  '1 Month',
  '3 Months',
  '6 Months',
  '1 Year',
  '2 Years',
  '3 Years',
  'Other'
];

// Comprehensive list of Malawi organisations / institutions
export const MALAWI_ORGANIZATIONS = [
  // Government Ministries & Departments
  'Government of Malawi',
  'Ministry of Finance and Economic Affairs',
  'Ministry of Health',
  'Ministry of Education',
  'Ministry of Agriculture',
  'Ministry of Natural Resources and Climate Change',
  'Ministry of Justice and Constitutional Affairs',
  'Ministry of Home Affairs',
  'Ministry of Foreign Affairs',
  'Ministry of Trade and Industry',
  'Ministry of Transport and Public Works',
  'Ministry of Local Government',
  'Ministry of Gender, Community Development and Social Welfare',
  'Ministry of Labour',
  'Ministry of Lands',
  'Ministry of Energy',
  'Ministry of Information and Digitalization',
  'Ministry of Tourism',
  'Ministry of Youth and Sports',
  'Malawi Revenue Authority (MRA)',
  'Malawi National Examinations Board (MANEB)',
  'National Registration Bureau (NRB)',
  'Registrar General',
  'National Planning Commission',

  // Parastatals & Government Agencies
  'Electricity Supply Corporation of Malawi (ESCOM)',
  'Malawi Communications Regulatory Authority (MACRA)',
  'Reserve Bank of Malawi (RBM)',
  'Malawi Investment and Trade Centre (MITC)',
  'Agricultural Development and Marketing Corporation (ADMARC)',
  'Malawi Housing Corporation (MHC)',
  'Smallholder Farmers Fertilizer Revolving Fund of Malawi (SFFRFM)',
  'National Water Development Authority (NWDA)',
  'Blantyre Water Board',
  'Lilongwe Water Board',
  'Northern Region Water Board',
  'Central Region Water Board',
  'Malawi Posts Corporation',
  'Roads Fund Administration (RFA)',
  'Road Traffic and Safety Authority (RTSA)',
  'Malawi Tourism Council',
  'Malawi Bureau of Standards (MBS)',
  'Malawi Industrial Research and Technology Development Centre (MIRTDC)',
  'National Oil Company of Malawi (NOCMA)',
  'Petroleum Control Commission (PCC)',
  'National AIDS Commission (NAC)',
  'Malawi Human Rights Commission (MHRC)',
  'Malawi Electoral Commission (MEC)',
  'Anti-Corruption Bureau (ACB)',
  'Ombudsman',
  'Malawi Police Service',
  'Malawi Defence Force',
  'Malawi Prison Service',
  'National Statistical Office (NSO)',

  // Universities & Colleges
  'University of Malawi (UNIMA)',
  'Chancellor College',
  'College of Medicine (Kamuzu University of Health Sciences)',
  'Polytechnic (Malawi University of Business and Applied Sciences - MUBAS)',
  'Lilongwe University of Agriculture and Natural Resources (LUANAR)',
  'Mzuzu University (MZUNI)',
  'Catholic University of Malawi (CUNIMA)',
  'Adventist University of Africa - Malawi Campus',
  'Daeyang Luke University',
  'DMI-St. John the Baptist University',
  'Malawi Assemblies of God University (MAGU)',
  'Nkhomaiversity University',
  'Unicaf University (Malawi)',
  'African Bible College',
  'Malawi College of Accountancy (MCA)',
  'Malawi College of Health Sciences (MCHS)',
  'Malawi Institute of Education (MIE)',
  'Staff Development Institute (SDI)',
  'Technical, Entrepreneurial and Vocational Education and Training Authority (TEVETA)',

  // Banks & Financial Institutions
  'National Bank of Malawi (NBM)',
  'Standard Bank Malawi',
  'FDH Bank',
  'NBS Bank',
  'CDH Investment Bank',
  'Opportunity Bank Malawi',
  'First Capital Bank Malawi',
  'Ecobank Malawi',
  'Malawi Savings Bank (MSB)',
  'OIBM (Opportunity International Bank of Malawi)',
  'FINCA Malawi',
  'MUSCO (Malawi Union Savings and Credit)',
  'MASM Medi Investments',
  'Pension Fund Management Company',
  'NICO Life Insurance',
  'NICO General Insurance',
  'Madison Life Insurance',
  'Old Mutual Malawi',
  'Britam Malawi',

  // NGOs & International Organizations
  'United Nations (UN) Malawi',
  'UNDP Malawi',
  'UNICEF Malawi',
  'WHO Malawi',
  'WFP Malawi',
  'UNHCR Malawi',
  'FAO Malawi',
  'ILO Malawi',
  'IOM Malawi',
  'World Bank Malawi',
  'IMF Malawi',
  'African Development Bank (AfDB)',
  'European Union (EU) Delegation Malawi',
  'USAID Malawi',
  'GIZ Malawi',
  'DFID / UK Aid Malawi',
  'Plan International Malawi',
  'Save the Children Malawi',
  'World Vision Malawi',
  'Oxfam Malawi',
  'Care International Malawi',
  'ActionAid Malawi',
  'Catholic Relief Services (CRS) Malawi',
  'MSF (Médecins Sans Frontières) Malawi',
  'Partners in Health (PIH) Malawi',
  'FHI 360 Malawi',
  'PATH Malawi',
  'JHPIEGO Malawi',
  'Concern Universal Malawi',
  'Tearfund Malawi',
  'Total Land Care (TLC)',
  'Malawi Red Cross Society',
  'Malawi Council for the Handicapped (MACOHA)',
  'Centre for Social Concern (CfSC)',
  'CARD (Community Action for Rural Development)',
  'Malawi Economic Justice Network (MEJN)',
  'Civil Society Agriculture Network (CISANET)',
  'Centre for Human Rights and Rehabilitation (CHRR)',

  // Telecom & ICT
  'Airtel Malawi',
  'TNM (Telekom Networks Malawi)',
  'Access Communications (Tnm)',
  'Skyband Corporation',
  'Globe Internet',
  'Malawi Telecomunications Limited (MTL)',

  // Retail, FMCG & Manufacturing
  'Illovo Sugar Malawi',
  'Press Corporation Limited (PCL)',
  'National Investment Trust (NIT)',
  'Carlsberg Malawi (Chibuku)',
  'Castel Malawi (Carlsberg/Chibuku)',
  'National Milling Company',
  'Afcon Holdings',
  'Export Trading Group (ETG)',
  'Kachele Holdings',
  'Shoprite Malawi',
  'Game Stores Malawi',
  'PEP Stores Malawi',
  'People\'s Trading Centre (PTC)',
  'Peoples Supermarket',
  'Chipiku Plus',
  'Sana Foods',
  'Amaryllis Hotel',
  'Sunbird Tourism',
  'Protea Hotel by Marriott',
  'Ryalls Hotel',
  'Palm Beach Resort',

  // Healthcare
  'Kamuzu Central Hospital',
  'Queen Elizabeth Central Hospital (QECH)',
  'Mzuzu Central Hospital',
  'Zomba Central Hospital',
  'Nkhata Bay District Hospital',
  'Bwaila District Hospital',
  'Thyolo District Hospital',
  'St. Gabriel\'s Hospital',
  'Adventist Health Centre',
  'Mlambe Hospital',
  'DAPP Malawi',
  'Medicins du Monde',

  // Private Sector / Other
  'Deloitte Malawi',
  'KPMG Malawi',
  'PricewaterhouseCoopers (PwC) Malawi',
  'Ernst & Young (EY) Malawi',
  'Grant Thornton Malawi',
  'BDO Malawi',
  'Other'
];
